### ISSUE TITLE
Additional FIAT currency support

### ISSUE THREAD

**Issue by kepoly** [casinocoin/casinocoin#23]
Add support for the Canadian Dollar (and any other currency that may be seen fit or requested) in Settings > Display > Currency to show amounts in:

**Comment by ajochems** [comment]
Need to add it to the coininfo api first, then i will add it to the wallet. I will try to squeeze it in the v3 release

**Comment by ajochems** [comment]
Added CAD, GBP, AUD and NZD to API and wallet
