### ISSUE TITLE
compile on linux

### ISSUE THREAD

**Issue by buechling** [casinocoin/casinocoin#24]
you added a "fix" for linux recently.. but it does not work for me:

g++: error: unrecognized command line option ‘-std=c++14’

when i remove the flag, i get the error:

	g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/user/casinocoin/src -I/home/user/casinocoin/src/obj -IOME/deps/boost_1_60_0 -IOME/deps/db-5.1.29.NC/build_unix -IOME/deps/openssl-1.0.2g -IOME/deps/miniupnpc-1.9 -DUSE_IPV6=1 -I/home/user/casinocoin/src/leveldb/include -I/home/user/casinocoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/main.d -o obj/main.o main.cpp
	main.cpp: In function ‘CBlockTemplate* CreateNewBlock(const CScript&)’:
	main.cpp:4495:5: error: ‘unique_ptr’ is not a member of ‘std’
		 std::unique_ptr<CBlockTemplate> pblocktemplate(new CBlockTemplate());
		 ^
	main.cpp:4495:35: error: expected primary-expression before ‘>’ token
		 std::unique_ptr<CBlockTemplate> pblocktemplate(new CBlockTemplate());
									   ^
	main.cpp:4495:72: error: ‘pblocktemplate’ was not declared in this scope
		 std::unique_ptr<CBlockTemplate> pblocktemplate(new CBlockTemplate());
																			^
	main.cpp: In function ‘void CasinoCoinMiner(CWallet*)’:
	main.cpp:4863:9: error: ‘unique_ptr’ is not a member of ‘std’
			 std::unique_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
			 ^
	main.cpp:4863:39: error: expected primary-expression before ‘>’ token
			 std::unique_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
										   ^
	main.cpp:4863:89: error: ‘pblocktemplate’ was not declared in this scope
			 std::unique_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
																							 ^
	main.cpp: In function ‘CBlockTemplate* CreateNewBlock(const CScript&)’:
	main.cpp:4729:1: warning: control reaches end of non-void function [-Wreturn-type]
	 }
	 ^
	make: *** [obj/main.o] Error 1

so how can i compile?

**Comment by ajochems** [comment]
What Linux version and GCC version are you building on? Did you follow https://github.com/casinocoin/casinocoin/wiki/Compile-Linux-CLI

**Comment by buechling** [comment]
ah i did not find that.. great hint. thank you!

had GCC 4.8 and tried 4.9 - but oviously 5.0 is needed
this does the trick on ubuntu:

	sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
	sudo apt-get update
	sudo apt-get install gcc-5 g++-5
	sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
