### ISSUE TITLE
Compile on Ubuntu

### ISSUE THREAD

**Issue by zimbo123** [casinocoin/casinocoin#26]
Hello,
i try to install the Casinocoin-Wallet in my Ubuntu Linux over console.
The Ubuntu Version is 14.04.4 LTS. When i compile the wallet with  sudo make -f makefile.unix

I got following error

g++: error: unrecognized command line option '-std=c++14'
g++: error: unrecognized command line option '-std=c++14'
make[1]: *** [db/builder.o] Error 1
make[1]: Leaving directory `/home/csc/casinocoin-3.0.0.0/src/leveldb'
make: *** [leveldb/libleveldb.a] Error 2

Thank you for your help.

**Comment by ajochems** [comment]
Make sure you have GCC 5 installed. Have you followed the wiki at https://github.com/casinocoin/casinocoin/wiki/Compile-Linux-CLI

**Comment by zimbo123** [comment]
Hello,
thanks for your Reply. But i want install it on a Server, i don't have an graphical Interfaces.

**Comment by ajochems** [comment]
Thats what the wiki is all about, it will compile the linux Command Line Interface daemon.

**Comment by zimbo123** [comment]
OK, thanks, i found the mistake. I forgot the following steps

cd casinocoin/src/leveldb
make libleveldb.a libmemenv.a
