### ISSUE TITLE
error -2

### ISSUE THREAD

**Issue by jjj092353** [casinocoin/casinocoin#29]
resynched with new wallet:

```
root@smh-us-stratum:/usr/local/bin# casinocoind getblockcount
1578164
root@smh-us-stratum:/usr/local/bin# casinocoind getblockhash
error: {"code":-2,"message":"Safe mode: Warning: Displayed transactions may not be correct! You may need to upgrade, or other nodes may need to upgrade."}
root@smh-us-stratum:/usr/local/bin# casinocoind getbalance
error: {"code":-2,"message":"Safe mode: Warning: Displayed transactions may not be correct! You may need to upgrade, or other nodes may need to upgrade."}
root@smh-us-stratum:/usr/local/bin# casinocoind getbalance
error: {"code":-2,"message":"Safe mode: Warning: Displayed transactions may not be correct! You may need to upgrade, or other nodes may need to upgrade."}
root@smh-us-stratum:/usr/local/bin# ^C
root@smh-us-stratum:/usr/local/bin# 
```

**Comment by ajochems** [comment]
There are some nodes that report the same problem. We got those solved by executing the following steps, you might try the same:

- Download a full copy of the blockchain from the main seed from http://api.casinocoin.org/downloads/csc-blockchain.tar.gz
- Create a backup of the blocks and chainstate directories in your daemon data directory. 
- Create a backup of your wallet.dat file
- Then after the backup delete those two directories and extract the downloaded file in your datadir with: tar xvzf csc-blockchain.tar.gz
- Restart your daemon with the -rescan option. If you run a full tx index you may need to run with the -reindex option instead, just look at the debug.log file when starting.
- If your daemon is up to speed again stop and restart it without the -rescan option

**Comment by ajochems** [comment]
Has your issue been resolved?

**Comment by ajochems** [comment]
Guess it has as there is no response!
