### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by expert-soft** [casinocoin/casinocoin#31]
root@ubuntu ~/t/c/src# make -f makefile.unix
Building LevelDB ...
g++: error: unrecognized command line option ‘-std=c++14’
g++: error: unrecognized command line option ‘-std=c++14’
make[1]: **\* [db/builder.o] Error 1
make[1]: Leaving directory `/casinocoin/src/leveldb'
make: **\* [leveldb/libleveldb.a] Error 2

uname -a
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

uname -r
3.13.0-24-generic

uname -m
x86_64

**Comment by ajochems** [comment]
Sorry, missed your issue.
What OS and GCC version are you building with? Whats the output of: g++ -v
See https://github.com/casinocoin/casinocoin/wiki/Compile-Linux-CLI for more details.

**Comment by ajochems** [comment]
Guess it is no longer an issue as you did not respond or close the issue
