### ISSUE TITLE
Error When Compiling - After Update

### ISSUE THREAD

**Issue by daygle** [casinocoin/casinocoin#32]
After the recent update I am receiving the below error when compiling in Debian Jessie:-

/usr/bin/ld: cannot find -lboost_system-mt
/usr/bin/ld: cannot find -lboost_filesystem-mt
/usr/bin/ld: cannot find -lboost_program_options-mt
/usr/bin/ld: cannot find -lboost_thread-mt
collect2: error: ld returned 1 exit status
makefile.unix:211: recipe for target 'casinocoind' failed
make: **\* [casinocoind] Error 1

**Comment by ajochems** [comment]
The linker can not find the boost libraries. You have to use GCC 5 and Boost 1.60 with the latest version. Have you followed https://github.com/casinocoin/casinocoin/wiki/Compile-Linux-CLI ? I think Jessie already has the GCC 5 installed (check with: g++ -v) so you could skip:
sudo apt-get install gcc-5 g++-5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

**Comment by ajochems** [comment]
Guess it is no longer an issue as you did not respond or close the issue

**Comment by daygle** [comment]
No this is still an issue, I have reverted back to the previous commit. Like I said the current release has broken the build in Debian.

**Comment by ajochems** [comment]
Well, have you read my response at all? I did various builds on Jessy and it is definitly not broken! Go read the wiki page i indicated. The error you have is simply that the boost libraries can not be found.

If you did not follow the wiki you must check the paths in the makefile: casinocoin/src/makefile.unix

**Comment by daygle** [comment]
Yes I read your reply.

How do you explain it working perfectly fine on the exact same server with the previous commit then?

**Comment by daygle** [comment]
I just want to let you know that I'm not your stock standard wallet user, I am a pool owner with 20+ mining pools and I maintain wallets on a daily basis (Casinocoin is among them).

Give it a go yourself if you don't believe me, compile Casinocoin in Debian 8.

**Comment by ajochems** [comment]
The last commit made some changes to the Makefile including BOOST_LIB_SUFFIX=-mt so if your boost libraries have a different suffix it will not work and you'll get the error you have. What are the filenames of your boost libraries in stage/lib of your boost build directory?

**Comment by daygle** [comment]
I assume you are asking about this directory? /usr/include/boost

**Comment by ajochems** [comment]
I really need to know if you followed the Wiki at all? In that case you would have the correct Boost and LevelDB libraries in your $HOME/deps folder and that is where the Makefile expects them. If you did not build the dependencies from the correct indicated versions from the wiki but installed them from packages it will not work.
